# Generated by Django 5.1.1 on 2024-09-17 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='data4',
        ),
        migrations.AddField(
            model_name='formentry',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formentry',
            name='data2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='data3',
            field=models.IntegerField(),
        ),
    ]
