# Generated by Django 5.1.1 on 2024-09-17 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_formentry_data4_formentry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='data2',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='time',
            field=models.DateField(),
        ),
    ]
